### ISSUE TITLE
Pairing code 

### ISSUE THREAD

**Issue by Migguuel** [SuhailTechInfo/Suhail-Md#119]
Why is there no link for the pairing code?

**Comment by solomonprecious** [comment]
Please you should try and include link for pairing code for those of us that has camera issues and unable to scan QR code

**Comment by Migguuel** [comment]
Ok

Le mar. 30 janv. 2024, 16:47, solomonprecious ***@***.***> a
écrit :

**Comment by jimmypie** [comment]
Please you should try and include link for pairing code for those of us that has camera issues and unable to scan QR code
