### ISSUE TITLE
Auto welcome group messages 

### ISSUE THREAD

**Issue by Krusherk** [SuhailTechInfo/Suhail-Md#122]
It's sending welcomed messages to groups automatically

**Comment by SuhailTechInfo** [comment]
***Use Following Command to Disable `welcome message` in groups***
```
.welcome off
```

**Comment by Krusherk** [comment]
Ok thanks

**Comment by Abdulhazeem01** [comment]
How can I disable the auto welcome message in every group at once @SuhailTechInfo

**Comment by SuhailTechInfo** [comment]
> How can I disable the auto welcome message in every group at once @SuhailTechInfo

i have added an option in heroku app variables to `Disable Welcome` message
