### ISSUE TITLE
antifake :   process.env.FAKE_COUNTRY_CODE ||'3125726553

### ISSUE THREAD

**Issue by Qasimjiho** [SuhailTechInfo/Suhail-Md#16]
https://github.com/SuhailTechInfo/Suhail-Md/blob/26e0c87ad805c8f1d1f781c880da1f8d26b07f18/config.js#L36

**Comment by Riders004** [comment]
> https://github.com/SuhailTechInfo/Suhail-Md/blob/26e0c87ad805c8f1d1f781c880da1f8d26b07f18/config.js#L36

Change to +212

**Comment by SuhailTechInfo** [comment]
> > https://github.com/SuhailTechInfo/Suhail-Md/blob/26e0c87ad805c8f1d1f781c880da1f8d26b07f18/config.js#L36
> 
> Change to +212

basicaly the thing is that, this variable is not be used in suhail-md bot, coz i updated it, through a cmd, name "antifake", its a group cmd that allow for specific country users to  joinn that group
