### ISSUE TITLE
Cricket score

### ISSUE THREAD

**Issue by haseebakram786** [SuhailTechInfo/Suhail-Md#172]
Cricket score plugin isn't working.... please solve that issue...

**Comment by tec655** [comment]
In the thrilling match between the two cricketing powerhouses, India and England, held at the iconic Lord's Cricket Ground, spectators were treated to a spectacle of skill, determination, and fierce competition. Batting first, India set a formidable target with a commanding innings led by their star batsmen. However, England's bowlers showcased their prowess, taking crucial wickets and keeping the Indian batsmen in check[ psl live match today](https://watchpsllive.com/). As the match progressed, the pendulum swung back and forth, with both teams displaying moments of brilliance in the field. In the end, it was a nail-biting finish as England chased down the target in the final overs, securing a hard-fought victory to the delight of their fans. The match served as a testament to the unpredictable nature of cricket and left spectators on the edge of their seats until the very last ball.

**Comment by fzfda** [comment]
In the end, it was a nail-biting finish as England chased down the target in the final overs, securing a hard-fought victory to the delight of their fans. The match served as a testament to the unpredictable nature of cricket and left spectators on the edge of their seats until the very last ball.
