### ISSUE TITLE
Can’t open view once pictures 

### ISSUE THREAD

**Issue by midesquare02** [SuhailTechInfo/Suhail-Md#175]
![IMG_7196](https://github.com/SuhailTechInfo/Suhail-Md/assets/157732890/a4f387eb-f561-44ee-a1c0-d71007838735)

Once I reply .vv to a view once picture, it will still keep on telling me to reply to a view once picture 

Pls help fix this issue as soon as possible

**Comment by SuhailTechInfo** [comment]
> Pls help fix this issue as soon as possible

***Fixed that Issue!***

### Just Redeploy the bot to get updates!
