### ISSUE TITLE
ANTIDELETE

### ISSUE THREAD

**Issue by Hndrxx9993** [SuhailTechInfo/Suhail-Md#230]
Please add antidelete so all deleted messages will go to my number. Messages from me and others

**Comment by Teams0012** [comment]
Yes true
I need antidelete to go to my number only not in chats or groups

**Comment by SuhailTechInfo** [comment]
***hey @Hndrxx9993  @Teams0012, I think you never installed plugins for Suhail Md***

## Check Suhail-Md all plugins from bellow link
- Find and **Installl** `ANTIDELETE` plugin:
```
https://github.com/SuhailTechInfo/Suhail-Md-Media
```

**Comment by Princealaba** [comment]
> _**hey @Hndrxx9993 @Teams0012, I think you never installed plugins for Suhail Md**_
> 
> ## Check Suhail-Md all plugins from bellow link
> * Find and **Installl** `ANTIDELETE` plugin:
> 
> ```
> https://github.com/SuhailTechInfo/Suhail-Md-Media
> ```

Bro show tutorial
