### ISSUE TITLE
CAN YOU HELP ME WITH THE ISSUE I HAVE ON REPLIT

### ISSUE THREAD

**Issue by notmaddy06** [SuhailTechInfo/Suhail-Md#26]
/home/runner/Suhail-Md-1/node_modules/discord-xp/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js: 198
const err = new MongooseError(message);
MongooseError: Operation levels.findOne() buffering timed out after 10000ms at Timeout.<anonymous> (/home/runner/Suhail-Md-1/node_modules/discord-xp/node_modules/mongoose/lib/drivers/node-m
ongodb-native/collection.js:198:23) at listOnTimeout (node: internal/timers:564:17)
Node.js v18.12.1
repl process died unexpectedly: exit status 1

**Comment by SuhailTechInfo** [comment]
> /home/runner/Suhail-Md-1/node_modules/discord-xp/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js: 198 const err = new MongooseError(message); MongooseError: Operation levels.findOne() buffering timed out after 10000ms at Timeout. (/home/runner/Suhail-Md-1/node_modules/discord-xp/node_modules/mongoose/lib/drivers/node-m ongodb-native/collection.js:198:23) at listOnTimeout (node: internal/timers:564:17) Node.js v18.12.1 repl process died unexpectedly: exit status 1

basically that issue arrived when you not using Valid mongodb api key, but don't be worry about it,
in next update i'll fix all kinda errors, but now add a mongodb key to remove this error.
