### ISSUE TITLE
Levelup command 

### ISSUE THREAD

**Issue by amgtwizter** [SuhailTechInfo/Suhail-Md#276]
Please how can I disable levelup command?

**Comment by Zailanijm** [comment]
Yeah that's my issues too

**Comment by Demaki001** [comment]
Please how can I disable levelup command?

**Comment by Demaki001** [comment]
It keeps sending many  messages to groups

**Comment by Zailanijm** [comment]
And now the logo menu aren't working
Suhail the bot is getting unstable please
