### ISSUE TITLE
Music 

### ISSUE THREAD

**Issue by Davis-Drex** [SuhailTechInfo/Suhail-Md#286]
The music being downloaded when using .play doesn’t work on iPhone 
![521DC882-BD06-4916-81B3-89B5EF3E5EEB](https://github.com/SuhailTechInfo/Suhail-Md/assets/150936239/993f4fbd-5836-42d3-b64c-491b97c4a05b)
![Uploading 600B5466-BF38-446C-AD2B-B48F96BED8C7.png…]()

**Comment by TinasheXD** [comment]
Cool

**Comment by TinasheXD** [comment]
Marvelous

**Comment by Davis-Drex** [comment]
Any solution?
