### ISSUE TITLE
𝕻~ß𝖔𝖙`🤖

### ISSUE THREAD

**Issue by Manexxxie** [SuhailTechInfo/Suhail-Md#371]
Why did suhail ban IMG command

**Comment by Manexxie** [comment]
![IMG_20240330_100642_548(1)](https://github.com/SuhailTechInfo/Suhail-Md/assets/161763472/3ac17c9a-ec1e-4627-a779-86a960046f1d)

**Comment by Manexxie** [comment]
![IMG_20240330_100642_548(1)](https://github.com/SuhailTechInfo/Suhail-Md/assets/161763472/54e5f671-a17d-4580-be1e-d5e580c35b14)

**Comment by Manexxie** [comment]
𝕻~ß𝖔𝖙`🤖
