### ISSUE TITLE
Suhail you are ignoring me its Abraham

### ISSUE THREAD

**Issue by abrahamdw882** [SuhailTechInfo/Suhail-Md#377]
U aren't responding to me on WhatsApp bruh

**Comment by Princealaba** [comment]
> U aren't responding to me on WhatsApp bruh

Bro how do u deploy xlicon v2 bot
It bans my heroku acc

**Comment by SuhailTechInfo** [comment]
> U aren't responding to me on WhatsApp bruh

## when and where ?

***BASICALLY MY WHATSAPP ACCOUNT IS BANNNED***
***thats why not available to reply!***
