### ISSUE TITLE
How to add your external logins to ur forked repository 

### ISSUE THREAD

**Issue by Princealaba4** [SuhailTechInfo/Suhail-Md#379]
I want antidelete

**Comment by ThwnOwFa** [comment]
SUHAIL_16_30_04_01_ewogICJjcmVkcy5qc29uIjogIntcIm5vaXNlS2V5XCI6e1wicHJpdmF0ZVwiOntcInR5cGVcIjpcIkJ1ZmZlclwiLFwiZGF0YVwiOlwiNkdva2JBNDFGKy9ZU2gyR09GeU5WWVJRL21zdTlyOERjNzNpOGxFSjNrOD1cIn0sXCJwdWJsaWNcIjp7XCJ0eXBlXCI6XCJCdWZmZXJcIixcImRhdGFcIjpcImMxMktLbGRDMjBxcVpZYkk0bGpDVXdPVlkxQyt6bDhlRXNNMlRyQzJha2M9XCJ9fSxcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6e1wicHJpdmF0ZVwiOntcInR5cGVcIjpcIkJ1ZmZlclwiLFwiZGF0YVwiOlwidUQ5Rk9Nd1NKZEh5SlVkUU9kaEk3a2J6QnF6N0U0QXJMYnhEeTRLSEIxYz1cIn0sXCJwdWJsaWNcIjp7XCJ0eXBlXCI6XCJCdWZmZXJcIixcImRhdGFcIjpcImJud1lSYUdxOUF5elFBTWZabGR2ZjkyV05UTllOSklJdW9kckZudXd6U3c9XCJ9fSxcInNpZ25lZElkZW50aXR5S2V5XCI6e1wicHJpdmF0ZVwiOntcInR5cGVcIjpcIkJ1ZmZlclwiLFwiZGF0YVwiOlwiZUswYzA2VEFqNnVrbGlWbCtsS3NOMmdZbG1Ja0VCQTlTM2VoOXlPRGVrMD1cIn0sXCJwdWJsaWNcIjp7XCJ0eXBlXCI6XCJCdWZmZXJcIixcImRhdGFcIjpcIkZiYjcvTVgybEVsSERVTHVnNGtQS3VzRVE2cjYzVkpzbDhneUdrbGR4QWs9XCJ9fSxcInNpZ25lZFByZUtleVwiOntcImtleVBhaXJcIjp7XCJwcml2YXRlXCI6e1widHlwZVwiOlwiQnVmZmVyXCIsXCJkYXRhXCI6XCJDRUZMbnpLS2lzdUM2UmNlQnhJeVJhVHRtcmlsSFVDWTBoNjNVdnRlcG1JPVwifSxcInB1YmxpY1wiOntcInR5cGVcIjpcIkJ1ZmZlclwiLFwiZGF0YVwiOlwiWjJJQ08xUWxnZExZd1VFaHgxSDYrU01yQmZtVm85dSsyL2hZN3M3UHJYbz1cIn19LFwic2lnbmF0dXJlXCI6e1widHlwZVwiOlwiQnVmZmVyXCIsXCJkYXRhXCI6XCJJSFNQanZpWkhPcUo1TzZXRzlJZ3pqS014YlpTODhtQzhhWHR4Y050bG9FMzluVWlRb0E1djhsU3RpUTc0WHVIa2RjUVQ4dlcrQ0Z2K1E5NkFSSVlpdz09XCJ9LFwia2V5SWRcIjoxfSxcInJlZ2lzdHJhdGlvbklkXCI6MjEzLFwiYWR2U2VjcmV0S2V5XCI6XCJ4cTlmOWtUSk9LOWl4S2pqWEtxR0Vvdmp5bFpGZG04RkRCN0FqSzRLVWVFPVwiLFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6W3tcImtleVwiOntcInJlbW90ZUppZFwiOlwiOTIzMjYyNTU2OTA0QHMud2hhdHNhcHAubmV0XCIsXCJmcm9tTWVcIjp0cnVlLFwiaWRcIjpcIjcwMDRDQUYwNzYzRDI0MjAwRTIxMzkxN0U1ODAyRUFBXCJ9LFwibWVzc2FnZVRpbWVzdGFtcFwiOjE3MTE5ODkwMDF9XSxcIm5leHRQcmVLZXlJZFwiOjMxLFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjozMSxcImFjY291bnRTeW5jQ291bnRlclwiOjAsXCJhY2NvdW50U2V0dGluZ3NcIjp7XCJ1bmFyY2hpdmVDaGF0c1wiOmZhbHNlfSxcImRldmljZUlkXCI6XCJuVUJyUnIzQVRyS1Bwc21TbnR2UWdBXCIsXCJwaG9uZUlkXCI6XCIyMGU0NDRmOC0yMGIyLTQ5NTItOTRlZS0wYThmZTg2OGMyZjNcIixcImlkZW50aXR5SWRcIjp7XCJ0eXBlXCI6XCJCdWZmZXJcIixcImRhdGFcIjpcIkVVV2FrbklobEswVVRIQkZ4Um00WTdRNWUvND1cIn0sXCJyZWdpc3RlcmVkXCI6dHJ1ZSxcImJhY2t1cFRva2VuXCI6e1widHlwZVwiOlwiQnVmZmVyXCIsXCJkYXRhXCI6XCJFS0cwWVdXZ0FVQXpXUXkwL2NCYUZiaGFncmM9XCJ9LFwicmVnaXN0cmF0aW9uXCI6e30sXCJwYWlyaW5nQ29kZVwiOlwiSjlGNVFUNDJcIixcIm1lXCI6e1wiaWRcIjpcIjkyMzI2MjU1NjkwNDo0QHMud2hhdHNhcHAubmV0XCIsXCJsaWRcIjpcIjI5ODgwNTU3MjQ0NTgyOjRAbGlkXCIsXCJuYW1lXCI6XCInX1xcXFw+8J2ZovCdmY0g8J2Zo/CdmYrwnZms8J2ZgfCdmZYg8J2ZmvCdmZMg8J2ZqPCdmYPwnZmW8J2ZnvCdmY/wnZmW8J2ZiSfwnZmsXCJ9LFwiYWNjb3VudFwiOntcImRldGFpbHNcIjpcIkNKRzk5YVVFRUlQQ3E3QUdHQUlnQUNnQVwiLFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOlwiZFdkQUpBakgrNDJ1SVhkZXZpN01BUFJBZkhrN0hjTmY3TTBnbU90MElXaz1cIixcImFjY291bnRTaWduYXR1cmVcIjpcImxja0VFdTJsZE5MWW80VW1jVDIvWlJQRUcrOFhMKzVUZlNIUEZlRUJaL1dTV1dDeDNaeXk1Z3ArQ0pzRFhSeXBDU3IyMWxVR3R0YnJJRnJCVlEvVUN3PT1cIixcImRldmljZVNpZ25hdHVyZVwiOlwieXR0aXZWQ2ZUdnB4YjVEMGpTa1dlTlQyUDBIZnFGd2RYN1M4QTdXczdPc095VllDZENYcm5PaytWSTQzK0RyTWNLbE5xZnVhYndlb2JVbEFnQ09GaEE9PVwifSxcInNpZ25hbElkZW50aXRpZXNcIjpbe1wiaWRlbnRpZmllclwiOntcIm5hbWVcIjpcIjkyMzI2MjU1NjkwNDo0QHMud2hhdHNhcHAubmV0XCIsXCJkZXZpY2VJZFwiOjB9LFwiaWRlbnRpZmllcktleVwiOntcInR5cGVcIjpcIkJ1ZmZlclwiLFwiZGF0YVwiOlwiQlhWblFDUUl4L3VOcmlGM1hyNHV6QUQwUUh4NU94M0RYK3pOSUpqcmRDRnBcIn19XSxcInBsYXRmb3JtXCI6XCJhbmRyb2lkXCIsXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjoxNzExOTg4OTk4LFwibXlBcHBTdGF0ZUtleUlkXCI6XCJBQUFBQUJVQVwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUJVQS5qc29uIjogIntcImtleURhdGFcIjpcIkFhU2pneHh6T2duK3duV01PK2xsUVlqdUdNRXliaVpGZTFjYXhrd1VXVWs9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTE1MzI2MTIwMSxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzExOTY4MDA1MTE4XCJ9Igp9

**Comment by SuhailTechInfo** [comment]
> I want antidelete

HELLO @Princealaba4 !

- go-to   [`External Plugins`](https://github.com/SuhailTechInfo/Suhail-Md-Media)
- search `Antidelete` plugin here!
- after that, use 
```
.instal antidelete_url // to install plugin
```
