### ISSUE TITLE
Work problem 

### ISSUE THREAD

**Issue by Muhamadadeel** [SuhailTechInfo/Suhail-Md#394]
Your bot is still Active but don't have any response not ping no work no status seen nothing but activate solve this  i am facing this

**Comment by SuhailTechInfo** [comment]
> Your bot is still Active but don't have any response not ping no work no status seen nothing but activate solve this i am facing this

### SOLUTION FOR THIS ISSUE
***If  this happens again, then***
- remove current device from whatsapp
- rescan qr or use pair code to get new session id
- use NEW SESSION_ID to resolve this issue
