### ISSUE TITLE
Stutas Seen problem 

### ISSUE THREAD

**Issue by suvo003** [SuhailTechInfo/Suhail-Md#516]
Auto stutas read is not working.
 And Auto stutas read option is not coming in heroku deploy method 
![Screenshot_20240429-194941](https://github.com/SuhailTechInfo/Suhail-Md/assets/166743391/9b4ee5bc-c17d-45fe-a80f-4ee3d8967279)

**Comment by SuhailTechInfo** [comment]
## To Enable auto read status : 
```
.readstatus on   // to enable
```
```
.readstatus off // to disable
```
