### ISSUE TITLE
Heroku accounts ban

### ISSUE THREAD

**Issue by bilalking99** [SuhailTechInfo/Suhail-Md#58]
Suhail Bhaai apka bot heroku ka account ban ker dita ha
Please yeh isssue solve krainn 
Aer session 🆔 ka bh msla ha 
Kabhii session 🆔 naiii atti ar kabhiii pairing Code mn msla
Hutta ha

**Comment by SuhailTechInfo** [comment]
huh, 
basically now suhail-Md run heroku very smoothly, 
coz i have fixed heroku ban problem

2nd:PAIRING AND SESSION ISSUE
   am already fixed that just 2 days ago, now you can run SUHAIL-MD without any worry

**Comment by bilalking99** [comment]
THANKS 🙏👍❤️❤️

**Comment by Partel6** [comment]
The repo is forked by once I enter my username it requests to be forked again

**Comment by SuhailTechInfo** [comment]
Maybe you changed the name of repository while fork,
Thats why it asking aggain and again for new fork.

# What next need to do
- Delete old fork .
- Then Create a `New Fork` !
- Don't Change the name for Repo.
