### ISSUE TITLE
Instagram Downloader Need?

### ISSUE THREAD

**Issue by mksir12** [SuhailTechInfo/Suhail-Md#59]
Can u add instagram Reel Download Plugin... 🙂

**Comment by SuhailTechInfo** [comment]
Ahhh, basically i have tried for it in last update, but didn't found any suited option for Insta Downloader, 
but i'll add this soon!

**Comment by SuhailTechInfo** [comment]
> Can u add instagram Reel Download Plugin... 🙂

# Insta Downloader plugin
```
https://gist.githubusercontent.com/SuhailTechInfo/4ecf80d5dfd264920117ca44a1917fe8/raw/7c2b2b1cafcf6a83b7ac8e33758a9c428bdd410a/instadl.js
```
