### ISSUE TITLE
QR CODE NOT LOADING 

### ISSUE THREAD

**Issue by Olawurld** [SuhailTechInfo/Suhail-Md#69]
![66525A29-4681-4538-9B28-7CE048BD38A9](https://github.com/SuhailTechInfo/Suhail-Md/assets/134863439/b32f4ab5-1ff0-45ac-ab62-4b791c095fab)

The QR code is not loading

**Comment by SuhailTechInfo** [comment]
ahh- i was just updating some masive things and mistakely deleted the qr from server.

But QR has beeen fixed now!
https://suhail-md-vtsf.onrender.com/
***Use above link to get qr for Suhail MD.***


Thanks for reporting the issue!

**Comment by Olawurld** [comment]
Congratulations!
