### ISSUE TITLE
Deployed but not working

### ISSUE THREAD

**Issue by Busybrain05** [SuhailTechInfo/Suhail-Md#72]
I've been deploying for the past 3days on heroku but not working its not bringing out any command

**Comment by SuhailTechInfo** [comment]
- wait for 2 minutes after installing the bot, then try. `Due to baileys Buffering!`
- If not works, then try to restart the bot.


- If still issues then try to scan Again.... `Sometimes session id expires`

**Comment by ayaan381** [comment]
Scanned but not working

**Comment by ayaan381** [comment]
Plz solve issu not working after scane

**Comment by SuhailTechInfo** [comment]
> Plz solve issu not working after scane

**Hey Buddy!**
This issue has been fixed in last update,
Just *REDEPLOY* the bot,
