### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VinRuchie** [SuhailTechInfo/Suhail-Md#76]
Which procedure will I follow to use the bot for Whatsapp status viewing?

**Comment by Omolexy** [comment]
How to deploy

**Comment by VinRuchie** [comment]
Yeah, procedure on how to deploy

**Comment by Omolexy** [comment]
procedure on how to deploy. I want to know

**Comment by SuhailTechInfo** [comment]
> Which procedure will I follow to use the bot for Whatsapp status viewing?

# if **HEROKU** then use:
```
 .setvar auto_read_status:true   // false for stop auto viewing 
```
OR 
```
 .newvar auto_read_status:true   // false for stop auto viewing 
```
# If not deployed on HEROKU:
- Otherwise Manully add a variable `AUTO_READ_STATUS` in you app,
-  Then Set Value `true` or `false` in it

**Comment by SuhailTechInfo** [comment]
> How to deploy


## Railway Deploy Tutorial For Suhail Md! 
**https://youtu.be/iGVdsK4qmcc**

## CodeSpace Deploy! 
**https://youtu.be/3NdJb6_1cJM**
