### ISSUE TITLE
Fork 

### ISSUE THREAD

**Issue by Tanela44** [SuhailTechInfo/Suhail-Md#92]
How can I create a fork

**Comment by SuhailTechInfo** [comment]
> How can I create a fork

- Open <a href="https://github.com/SuhailTechInfo/Suhail-Md"> SUHAIL MD</a> repository!
- `Star` the Repository!
- After that Click On `Fork` Button (Check below image)

***Check Highlighted Buttons Bellow*** <br><br>
![image](https://telegra.ph/file/4d6ca2b7ed1d5bd9bb28e.jpg)
