### ISSUE TITLE
[Help] Can't seem to connect, Self-hosting

### ISSUE THREAD

**Issue by kRystalDevv** [SuhailTechInfo/Suhail-Md#94]
```0|Suhail   |       [Symbol(errored)]: null,
0|Suhail   |       [Symbol(kHighWaterMark)]: 16384,
0|Suhail   |       [Symbol(kRejectNonStandardBodyWrites)]: false,
0|Suhail   |       [Symbol(kUniqueHeaders)]: null
0|Suhail   |     },
0|Suhail   |     _currentUrl: 'https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg',
0|Suhail   |     [Symbol(shapeMode)]: true,
0|Suhail   |     [Symbol(kCapture)]: false
0|Suhail   |   },
0|Suhail   |   response: undefined,
0|Suhail   |   isAxiosError: true,
0|Suhail   |   toJSON: [Function: toJSON]
0|Suhail   | }
0|Suhail   | ℹ️ Connecting to WhatsApp...
```

I created my sessionID, got message on whatsapp with my sessionID, created MongoDB and pasted that, it says Connected with MongoDB, idk what's left, it doesn't want to connect for some reason. I left it for 3 hours, it kept looping with that message. please help.

I'm running this on a raspberry pi, aarch64
Ubuntu 22.04
node: v20.11.0
npm: 10.2.4
yarn: 1.22.19
pm2: 5.3.1

**Comment by kRystalDevv** [comment]
```shell
0|Suhail   |   isAxiosError: true,
0|Suhail   |   toJSON: [Function: toJSON]
0|Suhail   | }
0|Suhail   | ℹ️ Connecting to WhatsApp...
0|Suhail   | Connection Lost from Server, reconnecting...
0|Suhail   | Suhail-Md Server listening on http://localhost:8224/
0|Suhail   |
0|Suhail   | Version Checking Successfull!
0|Suhail   |
0|Suhail   | ℹ️ Connecting to WhatsApp...
0|Suhail   | 🌍 Connected to the Mongodb.
0|Suhail   |
0|Suhail   | ERROR GETTING SESSION FROM PASTE SERVER
0|Suhail   |
0|Suhail   | Update'/home/pi/Suhail-Md/config.js'
``` 

idk if this helps, I recreated my sessionID, 

"SESSION_94_48_10_90_ExampleID" 
(i have to copy paste this entire thing right?)

**Comment by SuhailTechInfo** [comment]
> ```shell
> 0|Suhail   |   isAxiosError: true,
> 0|Suhail   |   toJSON: [Function: toJSON]
> 0|Suhail   | }
> 0|Suhail   | ℹ️ Connecting to WhatsApp...
> 0|Suhail   | Connection Lost from Server, reconnecting...
> 0|Suhail   | Suhail-Md Server listening on http://localhost:8224/
> 0|Suhail   |
> 0|Suhail   | Version Checking Successfull!
> 0|Suhail   |
> 0|Suhail   | ℹ️ Connecting to WhatsApp...
> 0|Suhail   | 🌍 Connected to the Mongodb.
> 0|Suhail   |
> 0|Suhail   | ERROR GETTING SESSION FROM PASTE SERVER
> 0|Suhail   |
> 0|Suhail   | Update'/home/pi/Suhail-Md/config.js'
> ```
> 
> idk if this helps, I recreated my sessionID,
> 
> "SESSION_94_48_10_90_ExampleID" (i have to copy paste this entire thing right?)


# Point  That need to follow:
---
- Make sure your device Connected with internet!
- Scan qr, then use Session id , that was sent to your whatsap,  instead of recraeting session
 **(Coz session ID Contains your connection variables, Soo you cant recrate a session Id)**
- also no need to use mongodb!

**Comment by kRystalDevv** [comment]
I managed to connect it, and it works, but commands like "help", "menu", don't output anything, A lot of commands don't work.
