### ISSUE TITLE
Npm not installing and not be deploying on replit 

### ISSUE THREAD

**Issue by hasanharal** [SuhailTechInfo/Suhail-Md#99]
![Screenshot_20240123-164138](https://github.com/SuhailTechInfo/Suhail-Md/assets/122716449/138c32e5-37a0-4f32-812d-7637e6617d0e)

It's showing error while deploying on replit please fix it 
It is not being deploy
npm is not being installed

**Comment by SuhailTechInfo** [comment]
# Try to reDeploy & Follow the Steps
- Fork the repository.
- Click on <a href="https://suhail-web01.vercel.app/replit.html">Deploy to Replit</a>.
- After import the repository, open `SHELL` in Replit.
- Run Below Commands
```
yarn   // For install Packages
```
```
yarn start     // For Run Bot
```

**Comment by hasanharal** [comment]
Pairing code option is not working please update
I have no multiple devices to scan qr
Please update pairing code
